from __future__ import annotations

import csv
import io
import uuid
from typing import Any

from mcp_hwc.pricing.models import QuoteItem, QuoteResult, ResourceDescriptor
from mcp_hwc.pricing.persistence import QuoteStore


_TERRAFORM_RESOURCE_MAP: dict[str, str] = {
    "ecs": "huaweicloud_compute_instance",
    "evs": "huaweicloud_evs_volume",
    "vpc": "huaweicloud_vpc",
    "eip": "huaweicloud_vpc_eip",
    "elb": "huaweicloud_elb_loadbalancer",
    "rds": "huaweicloud_rds_instance",
    "obs": "huaweicloud_obs_bucket",
    "cce": "huaweicloud_cce_cluster",
    "nat": "huaweicloud_nat_gateway",
    "dns": "huaweicloud_dns_zone",
    "kms": "huaweicloud_kms_key",
}


def export_csv(result: QuoteResult) -> str:
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow([
        "service", "resource_spec", "region", "period_type",
        "period_num", "quantity", "unit_price", "total_price", "currency",
    ])
    for item in result.items:
        writer.writerow([
            item.service,
            item.spec,
            item.region,
            item.period_type,
            item.period_num,
            item.quantity,
            item.unit_price,
            item.total_price,
            item.currency,
        ])
    return output.getvalue()


def export_json(result: QuoteResult) -> str:
    import json
    return json.dumps(result.to_dict(), indent=2)


def export_terraform(result: QuoteResult) -> str:
    lines = [
        '# Generated by mcp-hwc pricing tools',
        f'# Quote ID: {result.quote_id}',
        f'# Total monthly: ${result.total_monthly:.2f} USD',
        '',
    ]
    for i, item in enumerate(result.items):
        tf_type = _TERRAFORM_RESOURCE_MAP.get(item.service, f"huaweicloud_{item.service}_resource")
        name = f"{item.service}_{i}"
        lines.append(f'resource "{tf_type}" "{name}" {{')
        lines.append(f'  region     = "{item.region}"')
        lines.append(f'  # spec: {item.spec}')
        lines.append(f'  # period: {item.period_type} x{item.period_num}')
        lines.append(f'  # quantity: {item.quantity}')
        lines.append(f'  # price: ${item.unit_price:.2f} USD/{item.period_type}')
        lines.append('}')
        lines.append('')

    return "\n".join(lines)


def format_text(result: QuoteResult) -> str:
    lines = [
        f"Quote {result.quote_id}",
        "=" * 60,
        "",
    ]
    for item in result.items:
        period_label = (
            f"{item.period_type} x{item.period_num}"
            if item.period_type != "on_demand"
            else "on-demand (hourly)"
        )
        lines.append(f"  {item.service} / {item.spec}")
        lines.append(f"    Region: {item.region}")
        lines.append(f"    Period: {period_label}")
        lines.append(f"    Qty:    {item.quantity}")
        lines.append(f"    Price:  ${item.unit_price:.2f} USD each")
        lines.append(f"    Total:  ${item.total_price:.2f} USD")
        lines.append("")

    lines.append("-" * 60)
    lines.append(f"  Monthly est: ${result.total_monthly:.2f} USD")
    lines.append(f"  Annual est:  ${result.total_annual:.2f} USD")
    return "\n".join(lines)
